### ISSUE TITLE
Refused to connect to 'https://robot.fwrdto.me/send' 

### ISSUE THREAD

**Issue by arjunkomath** [VP42/fwrdto.me#1]
It doesn't work in all websites, eg: https://medium.com/
```
Uncaught SecurityError: Failed to execute 'open' on 'XMLHttpRequest': Refused to connect to 'https://robot.fwrdto.me/send' because it violates the document's Content Security Policy.
```

**Comment by VP42** [comment]
Thank you for the feedback!

It is a known issue, which unfortunately occurs on other websites as well (Facebook...) as they do not allow external JS to be executed on their pages. 

I'll try to come up with a solution soon but that would need to rethink the process entirely.

**Comment by VP42** [comment]
I gave more thoughts about it and came up with a new solution which now works on Medium!

Don't hesitate to try the new version by creating another bookmarklet (you can use the same email address) :)
